import { Card } from "@/components/card/Card";
import CTA from "@/components/cta/CTA";
import { Footer } from "@/components/footer/Footer";
import { Header } from "@/components/header/Header";
import { Hero } from "@/components/hero/Hero";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <title>Guia de Leitura - Universidade Libertária</title>
        <link rel='shortcut icon' href='favicon.ico' type='image/x-icon' />
      </Head>

      <Header />
      <div className={styles.wrapper}>
        <main>
          <Hero />
        </main>
        <CTA />
        <Card />
      </div>
      <Footer />
    </>
  );
}
